backend:
  name: github
  repo: andreykaa/barsky-remont-site
  branch: main
  auth_type: implicit

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

site_url: https://stone-dekor-stroyka-remont.netlify.app

collections:
  # твои коллекции (gallery, blog, settings) оставь как есть